bot:
  name: new_body_bot
  token: ${TOKEN}

logging:
  level:
    org.springframework: INFO

server:
  port: 8870

spring:
  datasource:
    platform: postgresql
    driverClassName: org.postgresql.Driver
    url: ${POSTGRESQL_CONNECT_STRING:jdbc:postgresql://localhost:5432/body}
    username: ${POSTGRESQL_USERNAME:user}
    password: ${POSTGRESQL_PASSWORD:pass}
  liquibase:
    enabled: ${LIQUIBASE_ENABLED:true}
    default-schema: public
  jpa:
    show_sql: false
